name: basemodels
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - matplotlib==3.5.3
      - numpy==1.26.4
      - pandas==2.2.3
      - scikit-learn==1.6.0
      - seaborn==0.13.2
      - tensorflow-gpu==2.11.0
